# Generated by Django 4.0.1 on 2022-02-18 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_content'),
        ('blog', '0004_alter_post_content'),
        ('vacancy', '0004_alter_vacancy_content'),
        ('forum', '0003_alter_answer_content_alter_question_content'),
        ('news', '0004_alter_news_content'),
        ('users', '0002_remove_profile_events_alter_contacts_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogs', models.ManyToManyField(related_name='treasure', to='blog.Post')),
                ('events', models.ManyToManyField(related_name='treasure', to='events.Event')),
                ('news', models.ManyToManyField(related_name='treasure', to='news.News')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='treasure', to=settings.AUTH_USER_MODEL)),
                ('questions', models.ManyToManyField(related_name='treasure', to='forum.Question')),
                ('vacancies', models.ManyToManyField(related_name='treasure', to='vacancy.Vacancy')),
            ],
        ),
    ]
