# Generated by Django 4.0.1 on 2022-02-18 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_treasure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treasure',
            name='owner',
        ),
        migrations.AddField(
            model_name='profile',
            name='treasure',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.treasure'),
        ),
    ]
