# Generated by Django 4.0.1 on 2022-02-18 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_answer_content_alter_question_content'),
        ('vacancy', '0004_alter_vacancy_content'),
        ('events', '0005_alter_event_content'),
        ('blog', '0004_alter_post_content'),
        ('users', '0004_remove_treasure_owner_profile_treasure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='treasure',
        ),
        migrations.AddField(
            model_name='treasure',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='treasure',
            name='blogs',
            field=models.ManyToManyField(blank=True, null=True, related_name='treasure', to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='treasure',
            name='events',
            field=models.ManyToManyField(blank=True, null=True, related_name='treasure', to='events.Event'),
        ),
        migrations.AlterField(
            model_name='treasure',
            name='questions',
            field=models.ManyToManyField(blank=True, null=True, related_name='treasure', to='forum.Question'),
        ),
        migrations.AlterField(
            model_name='treasure',
            name='vacancies',
            field=models.ManyToManyField(blank=True, null=True, related_name='treasure', to='vacancy.Vacancy'),
        ),
    ]
