# Generated by Django 4.0.1 on 2022-02-22 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_is_active_alter_profile_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treasure',
            old_name='blogs',
            new_name='blog',
        ),
        migrations.RenameField(
            model_name='treasure',
            old_name='events',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='treasure',
            old_name='questions',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='treasure',
            old_name='vacancies',
            new_name='vacancy',
        ),
    ]
