# Generated by Django 3.2.9 on 2021-12-02 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Tədbir')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('starts_at', models.DateTimeField(verbose_name='Başlanma tarixi')),
                ('ends_at', models.DateTimeField(verbose_name='Sonlanma tarixi')),
                ('desc', models.TextField(verbose_name='Təsviri')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('organiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='vacancy.employer')),
                ('tags', models.ManyToManyField(related_name='events', to='blog.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=1024, verbose_name='Şərh')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tariix')),
                ('active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='e_comments', to=settings.AUTH_USER_MODEL, verbose_name='müəllif')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e_comments', to='events.event')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
