# Generated by Django 4.0.1 on 2022-02-22 02:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0005_alter_event_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='likes',
            field=models.ManyToManyField(related_name='liked_event', to=settings.AUTH_USER_MODEL),
        ),
    ]
