# Generated by Django 4.0.1 on 2022-01-22 00:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Məzmun')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaradılma tarixi')),
                ('drafted', models.BooleanField(default=False, verbose_name='Qaralama')),
                ('views', models.IntegerField(default=0, verbose_name='')),
                ('supports', models.IntegerField(default=0)),
                ('last_edited', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-date_created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Şərh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tariix')),
                ('active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Başlıq')),
                ('content', models.TextField(verbose_name='Məzmun')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaradılma tarixi')),
                ('drafted', models.BooleanField(default=False, verbose_name='Qaralama')),
                ('views', models.IntegerField(default=0, verbose_name='')),
                ('supports', models.IntegerField(default=0)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('closed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-date_created',),
                'abstract': False,
            },
        ),
    ]
