# Generated by Django 3.2.9 on 2021-12-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
