# Generated by Django 4.0.1 on 2022-02-22 02:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0003_alter_answer_content_alter_question_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='supports_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='supports_count',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='answer',
            name='supports',
        ),
        migrations.AddField(
            model_name='answer',
            name='supports',
            field=models.ManyToManyField(related_name='supported_answer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='question',
            name='supports',
        ),
        migrations.AddField(
            model_name='question',
            name='supports',
            field=models.ManyToManyField(related_name='supported_question', to=settings.AUTH_USER_MODEL),
        ),
    ]
