# Generated by Django 3.2.9 on 2021-12-02 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Adı')),
                ('founded_at', models.DateField(null=True, verbose_name='Yaradılma tarixi')),
                ('workers', models.ManyToManyField(related_name='works_at', to=settings.AUTH_USER_MODEL, verbose_name='Əməkdaşlar')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Başlıq')),
                ('content', models.TextField(verbose_name='Məzmun')),
                ('dead_line', models.DateField(null=True, verbose_name='Bitmə tarixi (YYYY-MM-DD)')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('freelance', models.BooleanField(verbose_name='Freelance imkanı')),
                ('contact', models.CharField(max_length=128, verbose_name='Əlaqə ünvanı')),
                ('min_salary', models.PositiveIntegerField(verbose_name='Minimal maaş')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='vacancy.employer')),
            ],
            options={
                'verbose_name': 'Vakansiya',
                'verbose_name_plural': 'Vakansiyalar',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Şərh')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tariix')),
                ('active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v_comments', to=settings.AUTH_USER_MODEL, verbose_name='müəllif')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v_comments', to='vacancy.vacancy')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
