# Generated by Django 4.0.1 on 2022-02-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='freelance',
            field=models.BooleanField(verbose_name='Remote imkanı'),
        ),
    ]
