# Generated by Django 3.2.9 on 2021-12-04 13:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='workers',
            field=models.ManyToManyField(blank=True, null=True, related_name='works_at', to=settings.AUTH_USER_MODEL, verbose_name='Əməkdaşlar'),
        ),
    ]
