# Generated by Django 4.0.1 on 2022-02-12 02:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancy', '0002_alter_vacancy_freelance'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employer',
            name='workers',
            field=models.ManyToManyField(blank=True, related_name='works_at', to=settings.AUTH_USER_MODEL, verbose_name='Əməkdaşlar'),
        ),
    ]
