# Generated by Django 3.2.9 on 2021-12-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211204_1555'),
        ('vacancy', '0002_alter_employer_workers'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='tags',
            field=models.ManyToManyField(related_name='vacancies', to='blog.Tag'),
        ),
    ]
