# Generated by Django 4.0.1 on 2022-02-15 07:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0003_vacancy_like_count_alter_employer_workers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
