# Generated by Django 4.0.1 on 2022-02-20 05:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancy', '0004_alter_vacancy_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='founded_at',
            field=models.DateField(blank=True, null=True, verbose_name='Yaradılma tarixi'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_vacancies', to=settings.AUTH_USER_MODEL),
        ),
    ]
