# Generated by Django 4.0.1 on 2022-02-24 05:22

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancy', '0005_alter_employer_founded_at_alter_vacancy_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=ckeditor.fields.RichTextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_vacancy', to=settings.AUTH_USER_MODEL),
        ),
    ]
