# Generated by Django 4.0.1 on 2022-02-24 05:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0006_remove_comment_image_alter_comment_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(verbose_name='Şərh'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
