# Generated by Django 3.0.8 on 2020-07-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200706_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20, verbose_name='tag')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
